# Exported from Render on 2025-10-23T15:30:52Z
version: "1"
services:
- type: web
  name: Business
  runtime: node
  repo: https://github.com/shinadev/Business
  plan: free
  envVars:
  - key: Value
    sync: false
  - key: Name
    sync: false
  region: oregon
  buildCommand: dotnet publish -c Release -o out
  startCommand: dotnet out/Business.dll
  autoDeployTrigger: commit
  rootDir: Business
