# Exported from Render — Clean .NET Deployment Config
version: "1"

services:
  - type: web
    name: business
    env: docker
    plan: free
    region: oregon
    branch: master
    rootDir: .
    dockerfilePath: ./Dockerfile
    autoDeploy: true
